import { Component } from '@angular/core';

@Component({
  selector: 'spinner',
  templateUrl: './spinner.component.html',
  styleUrls: ['./spinner.component.css'],
})
export class SpinnerComponent {

  randomText: string = 'Getting your posts';

  randomTexts: string[] = [
    "Pay no attention to the man behind the curtain",
    "Follow the white rabbit",
    "The satellite is moving into position",
    "You're not in Bengal anymore",
    "Reticulating Splines",
    "The gods cannot contemplate your fate",
    "It's not you, it's me",
    "So, do you come here often?",
    "Counting backwards from infinity",
    "Rolling for initiative",
    "E.T. phone home",
    "May the force be with you",
    "Bravo 6, going dark",
    "Alright lads, keep it tight",
    "Here's looking at you, kid",
    "I'm gonna make you an offer you can't refuse",
    "Bond. James Bond.",
    "You're gonna need a bigger boat",
    "I'll be back",
    "Save the Green, Save the people!",
    "Open the pod bay doors, HAL",
    "Apna Sapna, Privacy Privacy",
    "Shaken, not stirred",
    "Parallel processors running perpendicular today",
    "Operation BlackBriar is in effect",
    "You can't handle the truth!",
    "Well, nobody's perfect",
    "Interference from lunar radiation",
    "Positron routers depleted",
    "Cyborg nanites infesting the server",
    "Astropneumatic oscillations inducing delays",
    "Increased sunspot activity",
    "Network packets were eaten by the terminator",
    "Network packets travelling uphill",
    "Trojan horse ran out of hay",
    "Change in the earth's rotational speed",
    "The servers sends their regards",
    "Firing up thrusters for increased exposure",
    "Houston, we hear you loud and clear",
    "Well, someone woke up on the wrong side of the bed",
    "Alright, alright, alright!",
    "This is not a DRILL!",
    "Smells like something's burning",
    "Solar flares disrupting data packets",
    "Looks like the server is having a bad day",
    "I am usually not this slow, believe me",
    "The server ate a clock, it's very time consuming",
    "Carpe Diem, user!",
    "Is this 221B, Baker Street?",
    "Country roads, take me to my feed",
    "Servers, assemble!",
    "Wormholes causing inter dimensional interference",
    "Engaging thermodynamic blasters in 3 .. 2 .. 1",
    "Unclogging the main transfer route",
    "Phew! So much traffic!",
    "Doppelgangers killing power in the server farm",
    "I'll be there for you when the data starts to pour",
    "Servers serving food today, not data",
    "The seas may be rough but I am the Captain",
    "Do you know that data is pronounced as data?",
    "You leave when I say you leave",
    "The stars are lost today",
    "By order of the Peaky Fookin' Servers!",
    'Say "hello" to my little friend!',
    "I feel the need - the need for speed!",
    "Bazinga!",
    "Accio data!",
    "Someone call the Ministry of Magic!",
    "And the Oscar goes to ... well, not the server",
    "Runtime exception thrown by the Large Hadron Collider",
    "Life is a box full of chocolates",
    "I am the one who knocks. I am the data!",
    "East or West? Tubu and Naru Best!",
    "They see me loading, They waiting!",
    "Recombobulating Discombobulators",
    "Achieving Nirvana",
    "Entering a state of biomorphic hyperturbulence",
    "Plan Paris has been activated",
    "Rounding up the discarded data chambers",
    "Do not go gentle into that good night",
    "The wait is worth it, we assure you"
  ];

  constructor() {
    this.randomText = this.randomTexts[Math.floor(Math.random() * (this.randomTexts.length - 0 + 1) + 0)];
  }
}
